### ISSUE TITLE
Small fixes and fine tuning after prod deployment

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#166]
## TODO

- [x] CI hotfix to merge to develop  
- [x] impossible to log in with eimis-admin user with the supposedly set password -> update admin password
- [x] grafana takes some time to be up and running causing grafana dashboard import to fail -> add a wait step

## Tests
- [x] Create a user and log in with `element.eimis.beta.gouv.fr`
- [x] Import some user with eimis tools, test forgot password
- [x] Use an android client (fluffy chat)
- [x] check monitoring
